// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace OctagonPlatform.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class TestToCreateANewPartner : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TestToCreateANewPartner));
        
        string IMigrationMetadata.Id
        {
            get { return "201708191639108_TestToCreateANewPartner"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
